from .board import *
from .change_password import *
from .file import *
from .file_create import *
from .file_delete import *
from .file_edit import *
from .file_upload import *
from .files import *
from .index import *
from .login import *
from .settings import *
from .profile import *
from .profile_delete import *
from .profile_edit import *
from .search import *
from .signout import *
from .signup import *
from .tasks import *